### ISSUE TITLE
Problem instrumenting infrastructure nodes

### ISSUE THREAD

**Issue by pahofmann** [Dynatrace/dynatrace-oneagent-operator#128]
We want to instrument the infrastructure nodes of our customers cluster to get insides into the OpenShift Router pods.  

We tagged them with the relevant node selectors (label apm=test in this case), which works fine for the worker nodes: 

```
  nodeSelector: 
    apm: test 
  # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/ (optional) 
  tolerations: 
  - effect: NoSchedule 
    key: node-role.kubernetes.io/master 
    operator: Exists
```

The node has the correct label and is not a master node:
```
$ oc describe node OurInfrastructureNode
Name:          OurInfrastructureNode
Roles:              infra 
Labels:             apm=test 
                    beta.kubernetes.io/arch=amd64 
                    beta.kubernetes.io/os=linux 
                    infra=true 
                    kubernetes.io/hostname=OurInfrastructureNode
                    logging-infra-fluentd=true 
                    node-role.kubernetes.io/infra=true 
                    region=infra 
                    router=yes 
                    zone=sztest 
Annotations: node.openshift.io/md5sum=efb9495187b03dc6x4bd217742d52cf1 
                    volumes.kubernetes.io/controller-managed-attach-detach=true 
```
Still no OneAgent is deployed to those nodes, there is no information about an deployment attempt in the logs.  
Are the infrastructure nodes excluded by other means?
