### ISSUE TITLE
Configure Namespace at Runtime

### ISSUE THREAD

**Issue by fanminshi** [Dynatrace/dynatrace-oneagent-operator#15]
I noticed that in your `main.go`:

```sh
sdk.Watch("dynatrace.com/v1alpha1", "OneAgent", "dynatrace", 120)
```

 https://github.com/Dynatrace/dynatrace-oneagent-operator/blob/master/cmd/dynatrace-oneagent-operator/main.go#L22

The namespace `"dynatrace"` is hardcoded. It might be a good idea for the operator pod to get the namespace from its environment so that the operator pod can be deployed in any namespace; unless the hardcoded namespace is intentional where you only want the operator to Watch the CR from the `"dynatrace"` namespace. 

To configure Namespace at Runtime, I would do the following:

Change main.go:

```go
namespace := os.Getenv("MY_POD_NAMESPACE")
sdk.Watch("dynatrace.com/v1alpha1", "OneAgent", namespace, 120)
```

and Operator.yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-oneagent-operator
  namespace: dynatrace
  labels:
    dynatrace: operator
    operator: oneagent
spec:
  replicas: 1
  selector:
....
  template:
....
    spec:
      containers:
        - name: dynatrace-oneagent-operator
       ...
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

ref: https://github.com/coreos/operator-sdk/issues/187
