### ISSUE TITLE
HTTP(S) Proxy Support

### ISSUE THREAD

**Issue by jamesmoriarty** [Dynatrace/dynatrace-oneagent-operator#202]
How do you configure the operator and operator agents to use a http proxy?
```
e.g. https_proxy=<protocol>://<user>:<password>@<host>:<port>
```
Our experience between install and running Dynatrace products is everything from PROXY, DT_PROXY, HTTP_PROXY, http_proxy, https_proxy, NO_PROXY, no_proxy, ProxyNonProxyHosts,...

**Comment by lrgar** [comment]
Hello there,

I believe you're also going through our Dynatrace Support team but for reference, at the moment, our suggested steps are to add environment variables as needed to the corresponding containers.

### Operator:
The manifest for the Operator deployment is included in our kubernetes.yaml file. 
* **https_proxy** environment variable: set to your proxy. Used to make some queries to the Dynatrace API.
* **no_proxy** environment variable: the Operator also makes requests to the Kubernetes API so **https_proxy** applies here as well. So set **no_proxy** to the endpoint used by Kubernetes API.

I was able to find the Kubernetes endpoint as an environment variable inside the container,

```bash
$ kubectl exec -n dynatrace -it deployments/dynatrace-oneagent-operator -- env | grep KUBERNETES_PORT_443_TCP_ADDR
KUBERNETES_PORT_443_TCP_ADDR=10.0.48.1
```

```yaml
containers:
- env:
  - name: https_proxy
    value: <proxy>
  - name: no_proxy
    value: 10.0.48.1
```

### OneAgent
This can be configured on the OneAgent CR objects directly:
* **https_proxy** environment variable: set to your proxy. This is used to download the agent.
* **--set-proxy** argument: set to your proxy. Passed to the OneAgent installer to configure the agent.

```yaml
spec:
  args:
  - --set-proxy=<proxy>
  env:
  - name: https_proxy
    value: <proxy>
```

Nonetheless, we have plans to improve the experience as well. Please continue with our Support team for further questions.

Best regards,
Luis

**Comment by jamesmoriarty** [comment]
@ingohackl A few points in regard to what you have told me:

- does `no_proxy` support?

Ranges:

```
no_proxy=10.0.0.0/8
```

Comma Separated IPs

```
1.2.3.4,5.6.7.8,...
```

- Also, when applying the proxy config to the operator I still see request not going via the proxy in the logs: `https://<tenency>/api/v1/deployment/installer/agent/unix/default/latest/metainfo?...`.

If I get a shell into the container and run `cat /proc/1/environ` I see the proxy config.

If I curl from the container to dynatrace it uses the proxy and succeeds. 

- Also, I've inlined the https_proxy like you've said above in the oneagent env resource. Am I correct it wont support the following format:

```
          - name: https_proxy
            valueFrom:
              secretKeyRef:
                name: oneagent
                key: http_proxy
```
